name: Compile C++

on:
  push

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/checkout@v4
      - name: Install g++
        run: sudo apt install gcc
      - name: Compile the file
        run: g++ file.cpp
